# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 295)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 81, 20))
        self.label_2.setObjectName("label_2")
        self.txt_sayi2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(70, 80, 200, 32))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.txt_sayi1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(70, 40, 200, 32))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.btn_Toplama = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Toplama.setGeometry(QtCore.QRect(70, 140, 75, 23))
        self.btn_Toplama.setObjectName("btn_Toplama")
        self.btn_cikarma = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_cikarma.setGeometry(QtCore.QRect(150, 140, 75, 23))
        self.btn_cikarma.setObjectName("btn_cikarma")
        self.btn_carpma = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_carpma.setGeometry(QtCore.QRect(230, 140, 75, 23))
        self.btn_carpma.setObjectName("btn_carpma")
        self.btn_bolme = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.btn_bolme.setObjectName("btn_bolme")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 190, 111, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sayı1 :"))
        self.label_2.setText(_translate("MainWindow", "Sayı2 :"))
        self.btn_Toplama.setText(_translate("MainWindow", "Toplama"))
        self.btn_cikarma.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_carpma.setText(_translate("MainWindow", "Çarpma"))
        self.btn_bolme.setText(_translate("MainWindow", "Bölme"))
        self.label_3.setText(_translate("MainWindow", "Sonuç :"))
